/*
    Part of the Raspberry-Pi Bare Metal Tutorials
    https://www.valvers.com/rpi/bare-metal/
    Copyright (c) 2013-2018, Brian Sidebotham

    This software is licensed under the MIT License.
    Please see the LICENSE file included with this software.

*/

#include <stdint.h>
#include "../include/rpi-uart.h"

typedef struct 
{
    char buf[50];
    int head;
    int tail;
    int size;
} fifo_t;

static rpi_aux_t* rpiAux = (rpi_aux_t*)RPI_AUX_BASE;
static rpi_uart_t* rpiMiniUart = (rpi_uart_t*)RPI_UART_BASE;
static fifo_t* writeBuffer, readBuffer;

rpi_aux_t* RPI_GetAux(void)
{
    return rpiAux;
}

rpi_uart_t* RPI_GetMiniUart(void)
{
    return rpiMiniUart;
}

void RPI_MiniUartInit(void)
{
    // Setup read and write buffers for mini UART

}

void RPI_WriteToMiniUart(char* string) 
{
    // Staring from index 0; add all characters to buffer
    char* ptr;

    for (ptr = string; *ptr != '\0'; ptr++) 
    {
        //first check if transmit buffer has enought space
        if (RPI_GetMiniUart()->AUX_MU_LSR_REG & 32) 
        {
            RPI_GetMiniUart()->AUX_MU_IO_REG = ptr;     // Write character to transmit buffer
        }
        
    }

    RPI_GetMiniUart()->AUX_MU_IER_REG |= 1 << 0;      // Enable transmit interrupt
}

void RPI_MiniUart_ISR(void) 
{
    volatile uint32_t incoming_byte;

    // Code executed if Mini UART receiver holds data
    if (RPI_GetMiniUart()->AUX_MU_IIR_REG & 4) {
        incoming_byte = RPI_GetMiniUart()->AUX_MU_IO_REG;
        // add to buffer

        RPI_GetMiniUart()->AUX_MU_IO_REG = incoming_byte;
    }

    // Interupt generated by transmit register being empty
    if (RPI_GetMiniUart()->AUX_MU_IIR_REG & 2) {
        // If transmit register is empty then check if transmit FIFO is empty
        // If transmit FIFO is empty the disable transmit interupt
        // Bit 6 in AUX_MU_LSR_REG is set high if transmit FIFO is empty
        if (RPI_GetMiniUart()->AUX_MU_LSR_REG & 64) {
            RPI_GetMiniUart()->AUX_MU_IER_REG &= ~(1 << 0);      // Disable transmit interrupt
        }
    }
}